### ISSUE TITLE
creating database step gives error

### ISSUE THREAD

**Issue by danrlu** [bacpop/PopPUNK#221]
**Versions**
poppunk                   2.5.0 
pp-sketchlib              2.0.0 

**Command used and output returned**
(I tried both my laptop and AWS EC2 with a fresh installation and got the same error)
```
conda create -n poppunk
conda activate poppunk
conda install poppunk
poppunk --create-db --output database --r-files r_file.txt --threads 8
```
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/20667188/191053121-f2d2ef0f-9642-4897-bfb1-141c8ac5c60f.png">

Whereas sketchlib works
<img width="1589" alt="image" src="https://user-images.githubusercontent.com/20667188/191053739-be3a1e87-8840-47cb-ba59-035783799ac4.png">

the content of `r_file.txt` (using the example data from Poppunk)
```
12673_8_24	12673_8#24.contigs_velvet.fa
12673_8_26	12673_8#26.contigs_velvet.fa
12673_8_27	12673_8#27.contigs_velvet.fa
12673_8_28	12673_8#28.contigs_velvet.fa
12673_8_29	12673_8#29.contigs_velvet.fa
12673_8_31	12673_8#31.contigs_velvet.fa
12673_8_32	12673_8#32.contigs_velvet.fa
12673_8_34	12673_8#34.contigs_velvet.fa
12673_8_36	12673_8#36.contigs_velvet.fa
12673_8_37	12673_8#37.contigs_velvet.fa
12673_8_39	12673_8#39.contigs_velvet.fa
12673_8_41	12673_8#41.contigs_velvet.fa
12673_8_42	12673_8#42.contigs_velvet.fa
12673_8_43	12673_8#43.contigs_velvet.fa
12754_4_66	12754_4#66.contigs_velvet.fa
12754_4_68	12754_4#68.contigs_velvet.fa
12754_4_70	12754_4#70.contigs_velvet.fa
12754_4_71	12754_4#71.contigs_velvet.fa
12754_4_73	12754_4#73.contigs_velvet.fa
12754_4_74	12754_4#74.contigs_velvet.fa
12754_4_75	12754_4#75.contigs_velvet.fa
12754_4_77	12754_4#77.contigs_velvet.fa
12754_4_78	12754_4#78.contigs_velvet.fa
12754_4_79	12754_4#79.contigs_velvet.fa
12754_4_80	12754_4#80.contigs_velvet.fa
12754_4_81	12754_4#81.contigs_velvet.fa
12754_4_82	12754_4#82.contigs_velvet.fa
12754_4_84	12754_4#84.contigs_velvet.fa
12754_4_85	12754_4#85.contigs_velvet.fa
12754_4_87	12754_4#87.contigs_velvet.fa
12754_4_88	12754_4#88.contigs_velvet.fa
12754_4_89	12754_4#89.contigs_velvet.fa
12754_4_90	12754_4#90.contigs_velvet.fa
12754_4_92	12754_4#92.contigs_velvet.fa
12754_4_94	12754_4#94.contigs_velvet.fa
12754_4_95	12754_4#95.contigs_velvet.fa
12754_5_11	12754_5#11.contigs_velvet.fa
12754_5_12	12754_5#12.contigs_velvet.fa
12754_5_13	12754_5#13.contigs_velvet.fa
12754_5_14	12754_5#14.contigs_velvet.fa
12754_5_16	12754_5#16.contigs_velvet.fa
12754_5_18	12754_5#18.contigs_velvet.fa
12754_5_19	12754_5#19.contigs_velvet.fa
12754_5_2	12754_5#2.contigs_velvet.fa
12754_5_20	12754_5#20.contigs_velvet.fa
12754_5_22	12754_5#22.contigs_velvet.fa
12754_5_24	12754_5#24.contigs_velvet.fa
12754_5_26	12754_5#26.contigs_velvet.fa
12754_5_28	12754_5#28.contigs_velvet.fa
12754_5_3	12754_5#3.contigs_velvet.fa
12754_5_30	12754_5#30.contigs_velvet.fa
12754_5_32	12754_5#32.contigs_velvet.fa
12754_5_33	12754_5#33.contigs_velvet.fa
12754_5_35	12754_5#35.contigs_velvet.fa
12754_5_36	12754_5#36.contigs_velvet.fa
12754_5_37	12754_5#37.contigs_velvet.fa
12754_5_39	12754_5#39.contigs_velvet.fa
12754_5_40	12754_5#40.contigs_velvet.fa
12754_5_42	12754_5#42.contigs_velvet.fa
12754_5_43	12754_5#43.contigs_velvet.fa
12754_5_45	12754_5#45.contigs_velvet.fa
12754_5_46	12754_5#46.contigs_velvet.fa
12754_5_47	12754_5#47.contigs_velvet.fa
12754_5_49	12754_5#49.contigs_velvet.fa
12754_5_5	12754_5#5.contigs_velvet.fa
12754_5_51	12754_5#51.contigs_velvet.fa
12754_5_52	12754_5#52.contigs_velvet.fa
12754_5_53	12754_5#53.contigs_velvet.fa
12754_5_55	12754_5#55.contigs_velvet.fa
12754_5_57	12754_5#57.contigs_velvet.fa
12754_5_59	12754_5#59.contigs_velvet.fa
12754_5_6	12754_5#6.contigs_velvet.fa
12754_5_61	12754_5#61.contigs_velvet.fa
12754_5_62	12754_5#62.contigs_velvet.fa
12754_5_64	12754_5#64.contigs_velvet.fa
12754_5_66	12754_5#66.contigs_velvet.fa
12754_5_68	12754_5#68.contigs_velvet.fa
12754_5_70	12754_5#70.contigs_velvet.fa
12754_5_71	12754_5#71.contigs_velvet.fa
12754_5_72	12754_5#72.contigs_velvet.fa
12754_5_73	12754_5#73.contigs_velvet.fa
12754_5_74	12754_5#74.contigs_velvet.fa
12754_5_76	12754_5#76.contigs_velvet.fa
12754_5_78	12754_5#78.contigs_velvet.fa
12754_5_8	12754_5#8.contigs_velvet.fa
12754_5_80	12754_5#80.contigs_velvet.fa
12754_5_82	12754_5#82.contigs_velvet.fa
12754_5_84	12754_5#84.contigs_velvet.fa
12754_5_86	12754_5#86.contigs_velvet.fa
12754_5_88	12754_5#88.contigs_velvet.fa
12754_5_89	12754_5#89.contigs_velvet.fa
12754_5_9	12754_5#9.contigs_velvet.fa
12754_5_90	12754_5#90.contigs_velvet.fa
12754_5_92	12754_5#92.contigs_velvet.fa
12754_5_94	12754_5#94.contigs_velvet.fa
12754_5_95	12754_5#95.contigs_velvet.fa
19183_4_48	19183_4#48.contigs_velvet.fa
19183_4_49	19183_4#49.contigs_velvet.fa
19183_4_50	19183_4#50.contigs_velvet.fa
19183_4_51	19183_4#51.contigs_velvet.fa
19183_4_52	19183_4#52.contigs_velvet.fa
19183_4_53	19183_4#53.contigs_velvet.fa
19183_4_54	19183_4#54.contigs_velvet.fa
19183_4_55	19183_4#55.contigs_velvet.fa
19183_4_56	19183_4#56.contigs_velvet.fa
19183_4_57	19183_4#57.contigs_velvet.fa
19183_4_58	19183_4#58.contigs_velvet.fa
19183_4_59	19183_4#59.contigs_velvet.fa
19183_4_60	19183_4#60.contigs_velvet.fa
19183_4_61	19183_4#61.contigs_velvet.fa
19183_4_62	19183_4#62.contigs_velvet.fa
19183_4_63	19183_4#63.contigs_velvet.fa
19183_4_64	19183_4#64.contigs_velvet.fa
19183_4_65	19183_4#65.contigs_velvet.fa
19183_4_66	19183_4#66.contigs_velvet.fa
19183_4_67	19183_4#67.contigs_velvet.fa
19183_4_68	19183_4#68.contigs_velvet.fa
19183_4_69	19183_4#69.contigs_velvet.fa
19183_4_70	19183_4#70.contigs_velvet.fa
19183_4_71	19183_4#71.contigs_velvet.fa
19183_4_72	19183_4#72.contigs_velvet.fa
19183_4_73	19183_4#73.contigs_velvet.fa
19183_4_74	19183_4#74.contigs_velvet.fa
19183_4_75	19183_4#75.contigs_velvet.fa
19183_4_76	19183_4#76.contigs_velvet.fa
19183_4_77	19183_4#77.contigs_velvet.fa
19183_4_78	19183_4#78.contigs_velvet.fa
19183_4_79	19183_4#79.contigs_velvet.fa
```

Full version list:
```
aom                       3.4.0                hb486fe8_1    conda-forge
atk-1.0                   2.36.0               he69c4ee_4    conda-forge
biopython                 1.79            py310h1961e1f_2    conda-forge
boost                     1.74.0          py310h509978a_5    conda-forge
boost-cpp                 1.74.0               h8b082ac_8    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
brotlipy                  0.7.0           py310h1961e1f_1004    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.9.14            h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            h904041c_1014    conda-forge
cairomm                   1.14.3               h694c41f_0    conda-forge
cairomm-1.0               1.14.3               hb8565cd_0    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h96bbf6e_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5           py310ha23aa8a_0    conda-forge
cryptography              37.0.4          py310h52c3658_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dendropy                  4.5.2              pyh3252c3a_0    bioconda
docopt                    0.6.2                      py_1    conda-forge
epoxy                     1.5.10               h5eb16cf_1    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
ffmpeg                    5.1.1           gpl_h5a1d76f_101    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h5bb23bf_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.2          py310h90acd4f_0    conda-forge
freetype                  2.12.1               h3f81eb7_0    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
gdk-pixbuf                2.42.8               hb161b9c_0    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
gfortran_impl_osx-64      11.3.0              h4c39eb8_25    conda-forge
glib-tools                2.72.1               h2292cb8_0    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.7.7                h047ecf1_0    conda-forge
graph-tool                2.45            py310h6327fc9_2    conda-forge
graph-tool-base           2.45            py310h054d7a2_2    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
gtk3                      3.24.34              h54007ae_1    conda-forge
h5py                      3.7.0           nompi_py310h56870fd_101    conda-forge
harfbuzz                  5.2.0                h52d05a2_0    conda-forge
hdbscan                   0.8.28          py310h81f86ea_1    conda-forge
hdf5                      1.12.2          nompi_hc782337_100    conda-forge
hicolor-icon-theme        0.17                 h694c41f_2    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
isl                       0.22.1               hb1e8313_2    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hac89ed1_2    conda-forge
kiwisolver                1.4.4           py310habb735a_0    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lame                      3.100             h35c211d_1001    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libcurl                   7.83.1               h372c54d_0    conda-forge
libcxx                    14.0.6               hccf4f1f_0    conda-forge
libdeflate                1.14                 hb7f2c08_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           10_4_0_h97931a8_25    conda-forge
libgfortran-devel_osx-64  11.3.0              h824d247_25    conda-forge
libgfortran5              11.3.0              h082f757_25    conda-forge
libgirepository           1.72.0               h0bde3a9_1    conda-forge
libglib                   2.72.1               hfbcb929_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libidn2                   2.3.3                hac89ed1_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libnghttp2                1.47.0               h7cbc4dc_1    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libpng                    1.6.38               ha978bb4_0    conda-forge
librsvg                   2.54.4               h3d48ba6_0    conda-forge
libsqlite                 3.39.3               ha978bb4_0    conda-forge
libssh2                   1.10.0               h7535e13_3    conda-forge
libtasn1                  4.19.0               hb7f2c08_0    conda-forge
libtiff                   4.4.0                hdb44e8a_4    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libvpx                    1.11.0               he49afe7_3    conda-forge
libwebp-base              1.2.4                h775f41a_0    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.14               hea49891_4    conda-forge
libzlib                   1.2.12               hfd90126_3    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
mandrake                  1.2.2           py310heea2105_1    conda-forge
matplotlib-base           3.6.0           py310he725631_0    conda-forge
mpc                       1.2.1                hbb51d92_0    conda-forge
mpfr                      4.1.0                h0f52abe_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nettle                    3.8.1                h96f3785_1    conda-forge
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
numpy                     1.23.3          py310h1b7c290_0    conda-forge
openblas                  0.3.21          openmp_hbefa662_3    conda-forge
openh264                  2.3.0                hb486fe8_0    conda-forge
openjpeg                  2.5.0                h5d0d7b0_1    conda-forge
openssl                   1.1.1q               hfe4f2af_0    conda-forge
p11-kit                   0.24.1               h65f8906_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4           py310hecf8f37_0    conda-forge
pango                     1.50.10              h1f197d0_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pillow                    9.2.0           py310h54af1cc_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
plotly                    5.10.0             pyhd8ed1ab_0    conda-forge
poppunk                   2.5.0           py310h0710ae5_0    bioconda
pp-sketchlib              2.0.0           py310hef20f8f_2    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pycairo                   1.21.0          py310h5138a19_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygobject                 3.42.2          py310h99dd5fd_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          ha7b0be1_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
rapidnj                   2.3.2                hcd10b59_2    bioconda
readline                  8.1.2                h3899abd_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scikit-learn              1.1.2           py310h3ba92a3_0    conda-forge
scipy                     1.9.1           py310h240c617_0    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
sigcpp-2.0                2.10.8               hf0c8a7f_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sparsehash                2.0.4                he49afe7_0    conda-forge
svt-av1                   1.2.1                hbbd2c75_0    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
treeswift                 1.1.28             pyh5e36f6f_0    bioconda
tzdata                    2022c                h191b570_0    conda-forge
unicodedata2              14.0.0          py310h1961e1f_1    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h775f41a_2    conda-forge
x265                      3.5                  hbb4e6a2_3    conda-forge
xorg-compositeproto       0.4.2             h0d85af4_1001    conda-forge
xorg-damageproto          1.2.1             h0d85af4_1002    conda-forge
xorg-fixesproto           5.0               h0d85af4_1002    conda-forge
xorg-inputproto           2.3.2             h35c211d_1002    conda-forge
xorg-kbproto              1.0.7             h35c211d_1002    conda-forge
xorg-libice               1.0.10               h0d85af4_0    conda-forge
xorg-libsm                1.2.3             h0d85af4_1000    conda-forge
xorg-libx11               1.7.2                h0d85af4_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxaw               1.0.14               h0d85af4_1    conda-forge
xorg-libxcomposite        0.4.5                h0d85af4_0    conda-forge
xorg-libxcursor           1.2.0                h0d85af4_0    conda-forge
xorg-libxdamage           1.1.5                h0d85af4_1    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xorg-libxext              1.3.4                h0d85af4_1    conda-forge
xorg-libxfixes            5.0.3             h0d85af4_1004    conda-forge
xorg-libxi                1.7.10               h0d85af4_0    conda-forge
xorg-libxinerama          1.1.4             he49afe7_1001    conda-forge
xorg-libxmu               1.1.3                h0d85af4_0    conda-forge
xorg-libxpm               3.5.13               h0d85af4_0    conda-forge
xorg-libxrandr            1.5.2                h0d85af4_1    conda-forge
xorg-libxrender           0.9.10            h0d85af4_1003    conda-forge
xorg-libxt                1.2.1                h0d85af4_2    conda-forge
xorg-randrproto           1.5.0             h0d85af4_1001    conda-forge
xorg-renderproto          0.11.1            h0d85af4_1002    conda-forge
xorg-util-macros          1.19.3               h35c211d_0    conda-forge
xorg-xextproto            7.3.0             h35c211d_1002    conda-forge
xorg-xproto               7.0.31            h35c211d_1007    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zlib                      1.2.12               hfd90126_3    conda-forge
zstandard                 0.18.0          py310h6c45266_0    conda-forge
zstd                      1.5.2                hfa58983_4    conda-forge
```

Let me know if anything else would be helpful!

**Comment by johnlees** [comment]
Thanks for the detailed report!

This is a problem with HDBSCAN, as it's coming from `import HDBSCAN`. Looks like it's due to an incompatibility with joblib version: https://github.com/scikit-learn-contrib/hdbscan/issues/562

Seems like they will release a fix at some point, but for now try:
```
conda install joblib==1.1.0
```
and hopefully it will work

**Comment by danrlu** [comment]
This worked! Thank you!

**Comment by mherold1** [comment]
The error message as text so it is easier to find this issue in the search:
```
Traceback (most recent call last):
  File "/opt/conda/miniconda3/envs/poppunk/bin/poppunk", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/__main__.py", line 213, in main
    from .models import loadClusterFit, BGMMFit, DBSCANFit, RefineFit, LineageFit
  File "/opt/conda/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/models.py", line 19, in <module>
    import hdbscan
  File "/opt/conda/miniconda3/envs/poppunk/lib/python3.10/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/opt/conda/miniconda3/envs/poppunk/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 509, in <module>
    memory=Memory(cachedir=None, verbose=0),
TypeError: Memory.__init__() got an unexpected keyword argument 'cachedir'
```

**Comment by gracehm** [comment]
Thanks for the fix! This still works!
