### ISSUE TITLE
issue with recent joblib update

### ISSUE THREAD

**Issue by jts1044** [bacpop/PopPUNK#238]
Hi, I just installed the new version of poppunk (2.5.0) and got this error when using --create-db: 

```
Traceback (most recent call last):
  File "/home/joshua.smith4/software/miniconda3/envs/poppunk/bin/poppunk", line 11, in <module>
    sys.exit(main())
  File "/home/joshua.smith4/software/miniconda3/envs/poppunk/lib/python3.9/site-packages/PopPUNK/__main__.py", line 213, in main
    from .models import loadClusterFit, BGMMFit, DBSCANFit, RefineFit, LineageFit
  File "/home/joshua.smith4/software/miniconda3/envs/poppunk/lib/python3.9/site-packages/PopPUNK/models.py", line 19, in <module>
    import hdbscan
  File "/home/joshua.smith4/software/miniconda3/envs/poppunk/lib/python3.9/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/joshua.smith4/software/miniconda3/envs/poppunk/lib/python3.9/site-packages/hdbscan/hdbscan_.py", line 509, in <module>
    memory=Memory(cachedir=None, verbose=0),
TypeError: __init__() got an unexpected keyword argument 'cachedir'
```
Upon checking the hdbscan github issues page, it appears that a recent joblib update from 1.1.0 to 1.2.0 causes this error. 
https://github.com/scikit-learn-contrib/hdbscan/issues/565

Downgrading this package to 1.1.0 seems to have fixed the problem. Just thought it would be worth giving a heads up in case others are running into this issue.

**Comment by jts1044** [comment]
Sorry, I missed the previous issue that already mentions this.
