### ISSUE TITLE
poppunk iterate: raise TypeError("multiplier must be an int or float")

### ISSUE THREAD

**Issue by luciagrami** [bacpop/PopPUNK#323]
Hello,
I am using poppunk 2.7.0 with pp-sketchlib v2.1.4.

I am having issues when running poppunk_iterate.py: poppunk_iterate.py --db PAdb --cutoff 0.2  --output PAit

Error: 

Traceback (most recent call last):
  File "/atlas/apps/miniconda3/envs/pp_env/bin/poppunk_iterate.py", line 257, in <module>
    tree.scale_edges(1 / max_pi)
  File "/atlas/apps/miniconda3/envs/pp_env/lib/python3.11/site-packages/treeswift/Tree.py", line 1169, in scale_edges
    raise TypeError("multiplier must be an int or float")
TypeError: multiplier must be an int or float

Any suggestions? Thanks!

**Comment by johnlees** [comment]
I'm guessing max_pi is coming out wrong. Can you add `print(max_pi)` to above line 257 and rerun?
