### ISSUE TITLE
Error when updating PopPUNK database without reference data

### ISSUE THREAD

**Issue by HarryHung** [bacpop/PopPUNK#325]
**Versions**
poppunk 2.6.3

**Command used and output returned**
```
poppunk_assign --update-db --db GPS_v9 --query query_for_v9_1_update.txt --external-clustering GPS_v9_external_clusters.csv  --output GPS_v9_1 --threads 32
```

An updated database is generated at the output directory, accompanying with this error
```
Traceback (most recent call last):
  File "/opt/conda/bin/poppunk_assign", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/PopPUNK/assign.py", line 211, in main
    assign_query(dbFuncs,
  File "/opt/conda/lib/python3.10/site-packages/PopPUNK/assign.py", line 307, in assign_query
    isolateClustering = assign_query_hdf5(dbFuncs,
  File "/opt/conda/lib/python3.10/site-packages/PopPUNK/assign.py", line 726, in assign_query_hdf5
    with open(ref_file_name) as refFile:
FileNotFoundError: [Errno 2] No such file or directory: 'GPS_v9/GPS_v9.refs'
```

**Describe the bug**

It is related to the usage of full-size (only) database for GPS Project GPSC assignment and its update. 

The source database does not have any reference data
```
tree GPS_v9

GPS_v9
├── GPS_v9_clusters.csv
├── GPS_v9.dists.npy
├── GPS_v9.dists.pkl
├── GPS_v9_fit.npz
├── GPS_v9_fit.pkl
├── GPS_v9_graph.gt
├── GPS_v9.h5
└── GPS_v9_unword_clusters.csv
```
It is fine to use for normal assignment, due to the automatic fallback of typical `poppunk_assign`:
> If the .refs file is missing, all of the samples in the sketch database will be used in the distance calculations.
https://github.com/bacpop/PopPUNK/blob/38b5d18bda389bd29cf20169a92042f129e68fc5/PopPUNK/assign.py#L455-L468

However, when running `--update-db`, even though the updated full-size database is saved in the first half of the function, the later part of function does not check whether `.ref `exists or not, and try to prune it, causing the error. 
https://github.com/bacpop/PopPUNK/blob/38b5d18bda389bd29cf20169a92042f129e68fc5/PopPUNK/assign.py#L755-L791

My question is, whether the updated database is safe to use despite the error? If so, could you please update the `poppunk_assign --update-db` process to handle this situation more elegantly? 

Thanks!

**Comment by johnlees** [comment]
Can you try with PopPUNK 2.7.0 and see if you get the same? I'm also working on a 'fast' update to meet a lot of your preferred criteria which will become available in 2.7.1, but it might be another couple of months before that is ready.

**Comment by johnlees** [comment]
The error above in 2.7.0 was also reported in #321 (seems to be related to newer versions of python, as it wasn't in changed code). I have PR #322 being prepared to fix it.

You could:
- make the quick fix suggested here and try again: https://github.com/bacpop/PopPUNK/issues/321#issuecomment-2295996548
- Wait until that PR is merged, which will become v2.7.1 (although to manage expectations, I actually think this will be Nov/Dec before done)
- Use the output from 2.6.3, which as you diagnose, I think should be fine if you just want the assignments. I am not confident it would create a correct updated database for further assignment however, and would need to check this further (which I don't currently have capacity to do)
- Another workaround would be to add a .refs file which just lists all the sample names

**Comment by HarryHung** [comment]
I think the last suggestion is the safest and least finicky route before v2.7.1 is out, so I tested it out (used v2.6.3 as it works without further modifications).

By adding a `.refs` that includes all samples, it allows the `poppunk_assign --update-db` to complete without error. 

A small side effect is it will lead to the generation of "reference" data within the output directory which is actually identical in size to the full size data (can be simply solved by running `rm *.refs*` afterward)

I further cross-checked this newly generated database against the previously generated database (the one generated without `.refs` and prematurely terminated by error).

All non-`csv` files have identical `md5sum` results, except `.h5`. Upon further inspection with `h5diff`, the content of both `.h5` are identical despite different `md5sum` results, Internet suggests `h5diff` is more reliable as it ignores metadata differences. For the `csv` files, the differences are caused by different sort order, the content is actually identical by sorting the rows (except `_unword_clusters.csv`, but I think it does not matter as long as `_clusters.csv`(?))

So I think the updated database is suitable for further assingment. Of course, I could just replace the existing database with the one generated without error just in case.

**Comment by HarryHung** [comment]
Issue has been solved when re-tested on v2.7.8, also with a greatly reduced database size (12GB -> 4.5GB) as `.dists.npy` is no longer needed. 

@johnlees  It seems the documentation needs to be updated regarding the change of `--update-db` which now requires a value instead of being a boolean option. Plus it would be nice to have more information on what the values mean in action.

Thanks!

**Comment by johnlees** [comment]
Thanks, good point! I've just added this
